edit('controller.v')
edit('filteredimage_ram.v')
edit('image_ram.v')
edit('kernel_ram.v')
edit('sop.v')
edit('convolve.v')

importhdl('controller.v')
importhdl('filteredimage_ram.v')
importhdl('image_ram.v')
importhdl('kernel_ram.v')
importhdl('sop.v')
importhdl('convolve.v')

addpath('hdlimport/controller');
open_system('controller.slx');
sim('controller.slx');
addpath('hdlimport/filteredimage_ram');
open_system('filteredimage_ram.slx');
sim('filteredimage_ram.slx');
addpath('hdlimport/image_ram');
open_system('image_ram.slx');
sim('image_ram.slx');
addpath('hdlimport/kernel_ram');
open_system('kernel_ram.slx');
sim('kernel_ram.slx');
addpath('hdlimport/sop');
open_system('sop.slx');
sim('sop.slx');
addpath('hdlimport/convolve');
open_system('convolve.slx');
sim('convolve.slx');